language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
    - "postgresql"
before_script:
  - "psql -c 'create database stayout;' -U postgres"
script:
  - npm ci
  - npm test
after_success: 
  - npm run coveralls
